# Generated by Django 4.0.3 on 2022-03-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
