# Generated by Django 4.0.3 on 2022-03-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0002_charity_customuser_first_name_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='Donor',
            new_name='donor',
        ),
    ]
